export default {
  config: {
    translations: {
      en: {
        "Auth.form.welcome.title": "Welcome to Inframap CMS!",
        "Auth.form.welcome.subtitle": "Log in to Inframap CMS",
        "app.components.LeftMenu.navbrand.title": "Inframap",
        "app.components.LeftMenu.navbrand.workplace": "Dashboard",
      },
    },
    locales: [
      "en",
      // 'ar',
      // 'fr',
      // 'cs',
      // 'de',
      // 'dk',
      // 'es',
      // 'he',
      // 'id',
      // 'it',
      // 'ja',
      // 'ko',
      // 'ms',
      // 'nl',
      // 'no',
      // 'pl',
      // 'pt-BR',
      // 'pt',
      // 'ru',
      // 'sk',
      // 'sv',
      // 'th',
      // 'tr',
      // 'uk',
      // 'vi',
      // 'zh-Hans',
      // 'zh',
    ],
  },
  bootstrap() {},
};
